# Change these first
owner: thewilloftheshadow
repo: utopium-status

# Add your sites here
sites:
  - name: Werewolf Utopium
    url: https://werewolf-utopium.tk
  - name: Spyfall Utopium
    url: https://spyfall.utopium.tk

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.utopium.tk
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Utopium Status
  introTitle: "Status Page for **Werewolf Utopium**"
  # introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: Server
      href: https://werewolf-utopium.tk/invite

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
